document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\"en\">");
document.writeln("<head>");
document.writeln("    <meta charset=\"UTF-8\">");
document.writeln("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
document.writeln("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">");
document.writeln("    <title>Document</title>");
document.writeln("    <link rel=\"stylesheet\" href=\"bootstrap/css/bootstrap.min.css\">");
document.writeln("    <link rel=\"stylesheet\" href=\"css/header&footer.css\">");
document.writeln("    <link rel=\"stylesheet\" href=\"css/common.css\">");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("    <footer>");
document.writeln("        <div class=\"container\">");
document.writeln("            <div class=\"footer_left\">");
document.writeln("                <div class=\"footer_tel\">");
document.writeln("                    <div class=\"tel_pic\">");
document.writeln("                        <img src=\"images/index_png_16.png\" alt=\"\">");
document.writeln("                    </div>");
document.writeln("                    <div class=\"tel_txt\">");
document.writeln("                        <p class=\"tel_number_txt\">加盟电话</p>");
document.writeln("                        <p class=\"tel_number\">400-153-5518</p>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <div class=\"footer_p\">");
document.writeln("                    <span>    版权所有：河北臻谷餐饮集团</span>   <span>冀ICP备12345678号-1 </span>  <span>技术支持：<a href=\"\">有度网络</a></span>");
document.writeln("                </div>");
document.writeln("");
document.writeln("            </div>");
document.writeln("            <div class=\"footer_right\">");
document.writeln("                <div class=\"footer_wx\">");
document.writeln("                    <div class=\"footer_wx_pic\">");
document.writeln("                        <img src=\"images/index_pic_32.jpg\" alt=\"\">");
document.writeln("                    </div>");
document.writeln("                    <p>扫一扫进群</p>");
document.writeln("                </div>");
document.writeln("                <div class=\"footer_wx\">");
document.writeln("                    <div class=\"footer_wx_pic\">");
document.writeln("                        <img src=\"images/index_pic_34.jpg\" alt=\"\">");
document.writeln("                    </div>");
document.writeln("                    <p>扫一扫关注公众账号</p>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </footer>");
document.writeln("</body>");
document.writeln("</html>");