document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\"en\">");
document.writeln("<head>");
document.writeln("    <meta charset=\"UTF-8\">");
document.writeln("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
document.writeln("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">");
document.writeln("    <title>Document</title>");
document.writeln("    <link rel=\"stylesheet\" href=\"bootstrap/css/bootstrap.min.css\">");
document.writeln("    <link rel=\"stylesheet\" href=\"css/header&footer.css\">");
document.writeln("    <link rel=\"stylesheet\" href=\"css/common.css\">");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("    <header>");
document.writeln("       <div class=\"container\">");
document.writeln("            <div class=\"inner\">");
document.writeln("                <a href=\"index.html\" class=\"header_log\">");
document.writeln("                    <img class=\"img-responsive\" src=\"images/log.png\" alt=\"\">");
document.writeln("                </a>");
document.writeln("                <nav>");
document.writeln("                    <ul>");
document.writeln("                        <li><a class=\"active_line\" href=\"index.html\">首页</a></li>");
document.writeln("                        <li><a href=\"about.html\">关于我们</a></li>");
document.writeln("                        <li><a href=\"culture.html\">品牌文化</a></li>");
document.writeln("                        <li><a href=\"news.html\">新闻动态</a></li>");
document.writeln("                        <li><a href=\"product.html\">新品上市</a></li>");
document.writeln("                        <li><a href=\"specialty.html\">特色菜肴</a></li>");
document.writeln("                        <li><a href=\"ours_ys.html\">加盟我们</a></li>");
document.writeln("                        <li><a href=\"recruit.html\">招纳贤才</a></li>");
document.writeln("                        <li><a href=\"contact.html\">联系我们</a></li>");
document.writeln("                    </ul>");
document.writeln("                </nav>");
document.writeln("                <div class=\"tel\">");
document.writeln("                    <div class=\"tel_pic\">");
document.writeln("                        <img src=\"images/tel_03.png\" alt=\"\">");
document.writeln("                    </div>");
document.writeln("                    <div class=\"tel_txt\">");
document.writeln("                        <p class=\"tel_number_txt\">加盟电话</p>");
document.writeln("                        <p class=\"tel_number\">400-153-5518</p>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <div class=\"nav_btn\"><i class=\"glyphicon glyphicon-list\"></i></div>");
document.writeln("            </div>");
document.writeln("       </div>");
document.writeln("    </header>");
document.writeln("</body>");
document.writeln("</html>");